// <auto-generated />
namespace wardrobeProject_test1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class shoesManage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(shoesManage));
        
        string IMigrationMetadata.Id
        {
            get { return "201604251242481_shoesManage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
